added docker-compose.yml file + Dockerfile for Innovation
csun-metalab/innovation pull request #75
Opened 2018-11-20 18:55 UTC by ebm17915

# DESCRIPTION
```
docker-compose.yml + Dockerfile for Innovation
```
# REQUIREMENTS & DEPENDENCIES
```
Have the docker-compose.yml file in Innovation directory
.env from web-demo server. Demo .env for this instance is best because it contains values necessary for innovation to fully display that are left missing in test .env "ALGOLIA_APP_ID"
```
# TESTING 

1. Clone innovation repository: `git clone https://github.com/csun-metalab/innovation.git`
2. Input testing .env
3. Import innovation's docker-compose.yml file if it isn't merged yet
4. Run `docker-compose up -d`

2018-11-21 19:47 UTC, digitalsoba requested changes
Tested with demo env; the test env gave back a 500, but demo is 👍. Confirmed yarn/npm installed and project is running. Just be sure to include the ticket number in the PR title and i'll approve.

2018-11-22 00:13 UTC, digitalsoba approved these changes

2018-11-22 03:01 UTC, ruizjorgealt commented
I was also testing this with the test .env and getting the 500 as well, I installed npm but not yarn. Didn't occur to me that it would require both. I am not very familiar with these two package managers, but my assumption was that one package manager should be installed per project, instead of multiple. 👍 Anyway, great job!

2018-12-04 21:15 UTC, ruizjorgealt approved these changes

2018-12-04 22:18 UTC, merged